const tiposColorPokemon = [
  { tipo: "all", color: "#D32C2C" },
  { tipo: "normal", color: "#A8A090" },
  { tipo: "fighting", color: "#A05038" },
  { tipo: "flying", color: "#98A8F0" },
  { tipo: "poison", color: "#B058A0" },
  { tipo: "ground", color: "#E9D6A4" },
  { tipo: "rock", color: "#B8A058" },
  { tipo: "bug", color: "#A8B820" },
  { tipo: "ghost", color: "#6060B0" },
  { tipo: "steel", color: "#A8A8C0" },
  { tipo: "fire", color: "#F05030" },
  { tipo: "water", color: "#3899F8" },
  { tipo: "grass", color: "#78C850" },
  { tipo: "electric", color: "#F8D030" },
  { tipo: "psychic", color: "#F870A0" },
  { tipo: "ice", color: "#58C8E0" },
  { tipo: "dragon", color: "#7860E0" },
  { tipo: "dark", color: "#000000" },
  { tipo: "fairy", color: "#E79FE7" },
  { tipo: "unknown", color: "#BC8F8F" },
  { tipo: "shadow", color: "#A9A9A9" },
];

export {tiposColorPokemon};